name: Cloud check in action
on:
  push:
    branches:
      - main
      - dev
  watch:
    types: started
  workflow_dispatch:
  schedule:
    - cron: 35 3 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
      - name: Generate random delay
        id: delay
        run: |
          # 生成 0 到 3600 秒之间的随机数
          RANDOM_DELAY=$((RANDOM % 3600))
          echo "Delaying for $RANDOM_DELAY seconds."
          echo "::set-output name=delay::$RANDOM_DELAY"
          sleep $RANDOM_DELAY  # 延迟执行
      - uses: actions/checkout@main
      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version: 18
      - name: init secrets
        uses: shine1594/secrets-to-env-action@master
        with:
          secrets: ${{ toJSON(secrets) }}
          secrets_env: production
          prefix_prod: ""
          file_name_prod: .env
      - name: init
        run: npm install
      - name: run
        id: run
        uses: nick-fields/retry@master
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm start
      - name: Keep Running
        run: |
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}
          git pull --rebase --autostash
          git commit --allow-empty -m "Keep Running..."
          git push
      - name: Delete old workflow run
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 50
